# POST  http://localhost:3001/api/v1/auth HTTP/1.1
# Content-Type: application/json

# {
#   "name": "minato",
#   "email": "mjhbad10@gmail.com",
#   "password": "asdfasdf"
# }

POST  http://localhost:3001/api/v1/auth/sign_in HTTP/1.1
Content-Type: application/json

{
  "name": "minato",
  "email": "mjhbad10@gmail.com",
  "password": "asdfasdf"
}

# POST  http://localhost:3001/api/v1/posts/28/likes HTTP/1.1
# Content-Type: application/json

# {
#   "access-token": "aMuPAsizkOl8Rzkcwc0wEQ",
#   "client": "D-b4oJRbYZDVulx18gGafw",
#   "uid": "mjhbad10@gmail.com"
# }